package br.com.infosolo.cobranca.enumeracao;

/**
 * Tipos de ocorrências permitidas no arquivos remessa / retorno.
 * 
 * @author Leandro Lima (leandro.lima@infosolo.com.br)
 *
 */
public enum TipoOcorrencia {
    // Ocorrencias para arquivo remessa
    REMESSA_REGISTRAR(1), // Registrar o titulo no banco
    REMESSA_BAIXAR(2), // Baixar o titulo no banco
    REMESSA_DEBITAR_EM_CONTA(3),
    REMESSA_CONCEDER_ABATIMENTO(4),
    REMESSA_CANCELAR_ABATIMENTO(5),
    REMESSA_CONCEDER_DESCONTO(6),
    REMESSA_CANCELAR_DESCONTO(7),
    REMESSA_ALTERAR_VENCIMENTO(8),
    REMESSA_PROTESTAR(9),
    REMESSA_CANCELAR_INSTRUCAO_PROTESTO(10),
    REMESSA_DISPENSAR_JUROS(11),
    REMESSA_ALTERAR_NOME_ENDERECO_SACADO(12),
    REMESSA_ALTERAR_NUMERO_CONTROLE(13),
    REMESSA_OUTRAS_OCORRENCIAS(14),

    // Ocorrências para arquivo retorno
    RETORNO_REGISTRO_CONFIRMADO(2),		// 02
    RETORNO_REGISTRO_RECUSADO(3),			// 03
    RETORNO_COMANDO_RECUSADO(0),			
    RETORNO_LIQUIDADO(6),					// 06
    RETORNO_LIQUIDADO_EM_CARTORIO(0),
    RETORNO_LIQUIDADO_PARCIALMENTE(0),
    RETORNO_LIQUIDADO_SALDO_RESTANTE(0),
    RETORNO_LIQUIDADO_SEM_REGISTRO(0),
    RETORNO_LIQUIDADO_POR_CONTA(0),
    RETORNO_BAIXA_SOLICITADA(0),
    RETORNO_BAIXADO(9),					// 09
    RETORNO_BAIXADO_POR_DEVOLUCAO(0),
    RETORNO_BAIXADO_FRANCO_PAGAMENTO(0),
    RETORNO_BAIXA_POR_PROTESTO(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_BAIXAR(0),
    RETORNO_BAIXA_OU_LIQUIDACAO_ESTORNADA(0),
    RETORNO_TITULO_EM_SER(11),				// 11
    RETORNO_RECEBIMENTO_INSTRUCAO_CONCEDER_ABATIMENTO(12),	// 12
    RETORNO_ABATIMENTO_CONCEDIDO(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_CANCELAR_ABATIMENTO(13),	// 13
    RETORNO_ABATIMENTO_CANCELADO(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_CONCEDER_DESCONTO(0),
    RETORNO_DESCONTO_CONCEDIDO(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_CANCELAR_DESCONTO(0),
    RETORNO_DESCONTO_CANCELADO(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_ALTERAR_DADOS(0),
    RETORNO_DADOS_ALTERADOS(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_ALTERAR_VENCIMENTO(14),	// 14
    RETORNO_VENCIMENTO_ALTERADO(0),
    RETORNO_ALTERACAO_DADOS_NOVA_ENTRADA(0),
    RETORNO_ALTERACAO_DADOS_BAIXA(0),
    RETORNO_LIQUIDACAO_TITULO_NAO_REGISTRADO(17),
    RETORNO_RECEBIMENTO_INSTRUCAO_PROTESTAR(15),			// 19
    RETORNO_PROTESTADO(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_SUSTAR_PROTESTO(20),		// 20
    RETORNO_PROTESTO_SUSTADO(0),
    RETORNO_INSTRUCAO_PROTESTO_REJEITADA_SUSTADA_OU_PENDENTE(0),
    RETORNO_DEBITO_EM_CONTA(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_ALTERAR_NOME_SACADO(0),
    RETORNO_NOME_SACADO_ALTERADO(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_ALTERAR_ENDERECO_SACADO(0),
    RETORNO_ENDERECO_SACADO_ALTERADO(0),
    RETORNO_ENCAMINHADO_A_CARTORIO(23),			// 23
    RETORNO_RETIRADO_DE_CARTORIO(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_DISPENSAR_JUROS(0),
    RETORNO_JUROS_DISPENSADOS(0),
    RETORNO_MANUTENCAO_TITULO_VENCIDO(0),
    RETORNO_RECEBIMENTO_INSTRUCAO_ALTERAR_TIPO_COBRANCA(0),
    RETORNO_TIPO_COBRANCA_ALTERADO(0),
    RETORNO_DESPESAS_PROTESTO(0),
    RETORNO_DESPESAS_SUSTACAO_PROTESTO(0),
    RETORNO_DEBITO_CUSTAS_ANTECIPADAS(0),
    RETORNO_CUSTAS_CARTORIO_DISTRIBUIDOR(0),
    RETORNO_CUSTAS_EDITAL(0),
    RETORNO_PROTESTO_OU_SUSTACAO_ESTORNADO(0),
    RETORNO_DEBITO_TARIFAS(0),
    RETORNO_ACERTO_DEPOSITARIA(0),
    RETORNO_OUTRAS_OCORRENCIAS(0);
    
    private int codigo;
    
    private TipoOcorrencia(int codigo) {
    	this.codigo = codigo;
    }

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}
}
